# Generated by Django 3.2.3 on 2023-10-17 20:11

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[core.validators.validate_username], verbose_name='Username'),
        ),
    ]
