version: '3.3'

volumes:
  pg_data_fdgrm:
  static:


services:
  backend:
    build: ../backend/foodgram_backend/
    env_file: ../backend/foodgram_backend/.env
    volumes:
      - static:/backend_static
      - ../backend/foodgram_backend/recipes/images/:/media
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/static
    command: cp -r /app/build/. /static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../backend/foodgram_backend/recipes/images/:/media
  db:
    image: postgres:13
    volumes:
      - pg_data_fdgrm:/var/lib/postgresql/data
    env_file: ../backend/foodgram_backend/.env

    
new:


version: '3.3'

volumes:
  pg_data_fdgrm:
  static:
  media:


services:
  backend:
    image: verapetrenko/foodgram_backend
    env_file: ../backend/foodgram_backend/.env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: verapetrenko/foodgram_frontend
    volumes:
      - ../frontend/:/static
    command: cp -r /app/build/. /static/
  nginx:
    image: nginx:1.19.3
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media
  db:
    image: postgres:13
    volumes:
      - pg_data_fdgrm:/var/lib/postgresql/data
    env_file: ../backend/foodgram_backend/.env


