version: '3.3'

# volumes:
  # pg_data_fdgrm:
  # static:


services:
  # backend:
  #   build: ../backend/foodgram_backend/
  #   env_file: ../backend/foodgram_backend/.env
  #   volumes:
  #     - static:/backend_static
  #     - ../backend/foodgram_backend/recipes/images/:/media
  #   depends_on:
  #     - db
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      # - 7000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ../backend/foodgram_backend/recipes/images/:/media
  # db:
  #   image: postgres:13
  #   volumes:
  #     - pg_data_fdgrm:/var/lib/postgresql/data
  #   env_file: ../backend/foodgram_backend/.env


