version: '3.3'

volumes:
  pg_data_fdgrm:
  static:
  media:


services:
  backend:
    image: verapetrenko/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  frontend:
    image: verapetrenko/foodgram_frontend
    volumes:
      - static:/static
    command: cp -r /app/build/. /static/
  nginx:
    image: verapetrenko/foodgram_nginx
    ports:
      - "7000:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
  db:
    image: postgres:13
    volumes:
      - pg_data_fdgrm:/var/lib/postgresql/data
    env_file: .env

